//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgeevPrakt17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Family { get; set; }
        public string Frist_name { get; set; }
        public string Last_name { get; set; }
        public short Group_number { get; set; }
        public string academic_discipline { get; set; }
        public int exercise___num { get; set; }
        public short hard_level { get; set; }
        public short grade { get; set; }
    }
}
